name = "ComparatorAutograder"
version = "0.1.0"
defaultTargets = ["comparatorautograder"]

[[lean_lib]]
name = "ComparatorAutograder"

[[lean_exe]]
name = "comparatorautograder"
root = "Main"

[[require]]
name = "comparator-autograder-lib"
git = "https://codeberg.org/xhalo32/comparator-autograder-lib.git"
rev = "40472499fc6f75c6ed58c46e8e7e9e3a00930a13"

[[require]]
name = "comparator"
git = "https://github.com/xhalo32/comparator"
# git = "file:///home/niklash/Projects/comparator"
rev = "ignore-missing"
