name = "ComparatorAutograder"
version = "0.1.0"
defaultTargets = ["comparatorautograder"]

[[lean_lib]]
name = "ComparatorAutograder"

[[lean_exe]]
name = "comparatorautograder"
root = "Main"

[[require]]
name = "comparator-autograder-lib"
git = "https://github.com/plclub/comparator-autograder-lib"
rev = "v4.34.0-rc2"

[[require]]
name = "comparator"
git = "https://github.com/xhalo32/comparator"
rev = "ignore-missing-4.34.0-rc2"
