name = "Demo"
version = "0.1.0"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[require]]
name = "comparator-autograder-lib"
git = "https://codeberg.org/xhalo32/comparator-autograder-lib.git"
rev = "40472499fc6f75c6ed58c46e8e7e9e3a00930a13"
